# Generated by Django 5.2.8 on 2025-11-26 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(default='20601234567', max_length=11, unique=True)),
                ('razon_social', models.CharField(default='Mi Bodega SAC', max_length=200)),
                ('regimen', models.CharField(choices=[('RUS', 'Nuevo RUS (Cuota fija)'), ('MYPE', 'MYPE Tributario'), ('RER', 'Régimen Especial')], default='RUS', max_length=10)),
                ('deuda_historica_sunat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('odoo_url', models.CharField(blank=True, help_text='Endpoint de AWS', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Para alertas de IA')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odoo_id', models.IntegerField(blank=True, help_text='ID externo en la BD de Odoo', null=True)),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('es_factura', models.BooleanField(default=False)),
                ('cliente_dni_ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', '🟡 Pendiente (Local)'), ('SYNCED', '🟢 Sincronizado (AWS)'), ('ERROR', '🔴 Error de Conexión')], default='PENDING', max_length=20)),
                ('odoo_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('log_respuesta', models.TextField(blank=True, help_text='Respuesta del servidor Odoo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.venta')),
            ],
        ),
    ]
